name: very_good_coffee
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  http: ^0.13.5
  equatable: ^2.0.0
  cached_network_image: ^3.2.3
  coffee_ui:
    path: packages/coffee_ui
  coffee_repository:
    path: packages/coffee_repository
  replay_bloc: ^0.2.2
  gallery_saver: ^2.3.2
  very_good_analysis: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.0
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

