name: weather_ui
description: UI Toolkit for esusu Weather App
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.1
