name: esusu_weather_app
description: "A simple yet elegant weather app."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  http: ^0.13.5
  equatable: ^2.0.5
  geolocator: ^10.1.0
  awesome_place_search: ^1.0.10
  google_maps_flutter: 2.5.2
  google_places_for_flutter: ^1.0.0
  search_map_place_updated: ^0.0.4
  weather_repository:
    path: packages/weather_repository
  weather_ui:
    path: packages/weather_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.0
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


